on: push
name: ğŸš€ Deploy website on pusha
jobs:
  web-deploy:
    name: ğŸ‰ Deploya
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.sourov.net
        username: git@sourov.net
        password: ${{ secrets.ftp_password }}
